title: Fanni Szabadi
url: https://szafanni.github.io
baseurl: 

author: Fanni Szabadi
description: My graphic UI design portfolio.

include: ['projects']

collections_dir: images

collections:
  illustrations:
    output: true
  web:
    output: true
  index:
    output: true

markdown: kramdown
kramdown:
  input: GFM
